/**
 * Generated by tsnapi — public API snapshot of `dsh-hono`
 */
// #region Interfaces
export interface HostServiceInstance<Options = undefined> {
  context: Context$1;
  options: Options;
}
// #endregion

// #region Types
export type HostService<Options = undefined> = (undefined extends Options ? (ctx: Context$1, options?: Options) => () => void : (ctx: Context$1, options: Options) => () => void) & {
  __host_instance?: HostServiceInstance<Options>;
};
// #endregion

// #region Functions
export declare function defineWebServer<Options = undefined>(_: (_: Hono) => void | Hono): HostService<Options>;
// #endregion