/**
 * Generated by tsnapi — public API snapshot of `dsh-hono/utils`
 */
// #region Functions
export declare function getServerContext<Options>(_: HostService<Options> | Context): Context$1;
export declare function getServerOptions<Options>(_: HostService<Options> | Context): Options;
// #endregion