/**
 * Generated by tsnapi — public API snapshot of `dsh-hono/utils`
 */
// #region Functions
export declare function getServerContext<Context$2 = Context$1>(_: HostService<any> | Context): Context$2;
export declare function getServerOptions<Options>(_: HostService<Options> | Context): Options;
// #endregion